"use client";
import { useMemo, useState } from "react";
import { ArrowRight, Check, Plus, Search, Trash2 } from "lucide-react";
import { tarefasMock } from "@/lib/mock-data";
import type { StatusTarefa, Tarefa } from "@/types";
import { dataBr } from "@/lib/utils";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
const colunas:{status:StatusTarefa;label:string;className:string}[]=[{status:"PENDENTE",label:"Pendentes",className:"kanban-pending"},{status:"EM_ANDAMENTO",label:"Em andamento",className:"kanban-progress"},{status:"CONCLUIDA",label:"Concluídas",className:"kanban-done"}];
export default function Tarefas(){const [tarefas,setTarefas]=useState<Tarefa[]>(tarefasMock),[busca,setBusca]=useState("");const filtradas=useMemo(()=>tarefas.filter(t=>(t.titulo+t.responsavelNome+t.categoria).toLowerCase().includes(busca.toLowerCase())),[tarefas,busca]);function mover(t:Tarefa){const proximo:StatusTarefa=t.status==="PENDENTE"?"EM_ANDAMENTO":"CONCLUIDA";setTarefas(x=>x.map(i=>i.id===t.id?{...i,status:proximo}:i))}function finalizar(id:string){if(confirm("Finalizar e excluir esta tarefa definitivamente?"))setTarefas(x=>x.filter(t=>t.id!==id))}return <><PageHeading title="Tarefas" description="Fluxo diário simples: avance, conclua e finalize." action={<button className="btn-primary"><Plus size={17}/>Nova tarefa</button>}/><div className="card mb-4 flex items-center gap-2 py-3"><Search size={17}/><input className="w-full bg-transparent outline-none" placeholder="Filtrar por tarefa, responsável ou categoria..." value={busca} onChange={e=>setBusca(e.target.value)}/></div><div className="grid gap-4 xl:grid-cols-3">{colunas.map(c=><section key={c.status} className={`rounded-2xl border p-3 ${c.className}`}><div className="mb-3 flex items-center justify-between"><b>{c.label}</b><span className="rounded-full bg-white/75 px-2 py-0.5 text-xs">{filtradas.filter(t=>t.status===c.status).length}</span></div><div className="space-y-3">{filtradas.filter(t=>t.status===c.status).map(t=><article key={t.id} className="rounded-xl border bg-card p-4 shadow-sm"><div className="mb-2 flex items-start justify-between gap-2"><h3 className="font-semibold">{t.titulo}</h3><StatusBadge status={t.prioridade}/></div><p className="text-xs text-foreground/50">{t.categoria} • {t.responsavelNome}</p><p className="mt-3 text-xs">Prazo: {dataBr(t.prazo)}</p>{t.status==="CONCLUIDA"?<button className="btn-primary mt-4 w-full" onClick={()=>finalizar(t.id)}><Trash2 size={16}/>Finalizar e descartar</button>:<button className="btn-outline mt-4 w-full" onClick={()=>mover(t)}>{t.status==="PENDENTE"?"Iniciar tarefa":"Marcar concluída"}{t.status==="EM_ANDAMENTO"?<Check size={16}/>:<ArrowRight size={16}/>}</button>}</article>)}</div></section>)}</div></>}
