"use client";
import { useMemo,useState } from "react";
import { CalendarCheck2,CheckCircle2,Pencil,Plus,Trash2,UserMinus,UserRoundPlus,X } from "lucide-react";
import { diaristasMock } from "@/lib/mock-data";
import type { Diarista } from "@/types";
import { moeda } from "@/lib/utils";
import { PageHeading } from "@/components/page-heading";
import { EntityTable } from "@/components/entity-table";
import { StatusBadge } from "@/components/status-badge";
import { TableFilter } from "@/components/table-filter";
type Escala={id:string;diaristaId:string;status:"PENDENTE"|"PAGO";valor:number};
export default function Diaristas(){
 const [lista,setLista]=useState<Diarista[]>(diaristasMock),[escalados,setEscalados]=useState<Escala[]>([]),[selecionado,setSelecionado]=useState(""),[buscaHoje,setBuscaHoje]=useState(""),[buscaCadastro,setBuscaCadastro]=useState(""),[modal,setModal]=useState(false),[confirmarDia,setConfirmarDia]=useState(false),[editando,setEditando]=useState<Diarista|null>(null);
 const cadastros=useMemo(()=>lista.filter(d=>(d.nome+d.cpf+d.chavePix).toLowerCase().includes(buscaCadastro.toLowerCase())),[lista,buscaCadastro]);
 const hoje=useMemo(()=>escalados.filter(e=>(lista.find(d=>d.id===e.diaristaId)?.nome||"").toLowerCase().includes(buscaHoje.toLowerCase())),[escalados,lista,buscaHoje]);
 function escalar(){const d=lista.find(i=>i.id===selecionado);if(!d||escalados.some(e=>e.diaristaId===d.id))return;setEscalados(a=>[{id:crypto.randomUUID(),diaristaId:d.id,status:"PENDENTE",valor:d.valorPadraoDiaria},...a]);setSelecionado("")}
 function salvar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d:Diarista={id:editando?.id||crypto.randomUUID(),nome:String(f.get("nome")),cpf:String(f.get("cpf")),telefone:String(f.get("telefone")),chavePix:String(f.get("pix")),banco:String(f.get("banco")),valorPadraoDiaria:Number(f.get("valor")),ativo:true};setLista(a=>editando?a.map(i=>i.id===d.id?d:i):[d,...a]);setModal(false);setEditando(null)}
 return <><PageHeading title="Diaristas" description="Escale o dia usando os profissionais já cadastrados." action={<button className="btn-primary" onClick={()=>{setEditando(null);setModal(true)}}><Plus size={17}/>Novo cadastro</button>}/>
 <section className="card mb-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="section-title">Diaristas de hoje</h2><p className="text-sm text-foreground/55">Selecione um cadastro para escalar e liberar o pagamento.</p></div><div className="scale-controls flex min-w-[300px] flex-1 justify-end gap-2"><select className="input max-w-sm" value={selecionado} onChange={e=>setSelecionado(e.target.value)}><option value="">Selecione um diarista...</option>{lista.filter(d=>!escalados.some(e=>e.diaristaId===d.id)).map(d=><option key={d.id} value={d.id}>{d.nome} — {moeda(d.valorPadraoDiaria)}</option>)}</select><button className="btn-primary" onClick={escalar} disabled={!selecionado}><UserRoundPlus size={17}/>Escalar</button></div></div>
 <TableFilter value={buscaHoje} onChange={setBuscaHoje} placeholder="Buscar na escala de hoje..."/><div className="diaristas-desktop"><EntityTable headers={["Nome","PIX","Valor","Pagamento","Ações"]}>{hoje.map(e=>{const d=lista.find(i=>i.id===e.diaristaId);return d&&<tr key={e.id}><td className="font-semibold">{d.nome}</td><td>{d.chavePix}</td><td>{moeda(e.valor)}</td><td><StatusBadge status={e.status}/></td><td><div className="flex gap-2"><button className="btn-outline" disabled={e.status==="PAGO"} onClick={()=>setEscalados(a=>a.map(i=>i.id===e.id?{...i,status:"PAGO"}:i))}><CheckCircle2 size={16}/>Pagar</button><button className="btn-danger-soft" onClick={()=>setEscalados(a=>a.filter(i=>i.id!==e.id))}><UserMinus size={16}/>Desvincular</button></div></td></tr>})}</EntityTable></div><div className="diaristas-mobile">{hoje.map(e=>{const d=lista.find(i=>i.id===e.diaristaId);return d&&<article key={e.id} className="diarista-mobile-card"><div className="diarista-mobile-head"><div><b>{d.nome}</b><small>{d.chavePix}</small></div><StatusBadge status={e.status}/></div><div className="diarista-mobile-value"><span>Diária</span><strong>{moeda(e.valor)}</strong></div><div className="diarista-mobile-actions"><button className="btn-outline" disabled={e.status==="PAGO"} onClick={()=>setEscalados(a=>a.map(i=>i.id===e.id?{...i,status:"PAGO"}:i))}><CheckCircle2 size={14}/>Pagar</button><button className="btn-danger-soft" onClick={()=>setEscalados(a=>a.filter(i=>i.id!==e.id))}><UserMinus size={14}/>Desvincular</button></div></article>})}</div>{!hoje.length&&<p className="py-5 text-center text-sm text-foreground/50">Nenhum diarista escalado para hoje.</p>}<div className="mt-4 border-t pt-4"><button className="btn-primary w-full" disabled={!escalados.length} onClick={()=>setConfirmarDia(true)}><CalendarCheck2 size={18}/>Finalizar o dia</button></div></section>
 <section><div className="mb-3"><h2 className="section-title">Cadastros de diaristas</h2><p className="text-sm text-foreground/55">Cadastre cada profissional uma única vez.</p></div><TableFilter value={buscaCadastro} onChange={setBuscaCadastro} placeholder="Buscar nome, CPF ou PIX nos cadastros..."/><div className="diaristas-desktop"><EntityTable headers={["Nome","CPF","Telefone","PIX / Banco","Diária","Status","Ações"]}>{cadastros.map(d=><tr key={d.id}><td className="font-semibold">{d.nome}</td><td>{d.cpf}</td><td>{d.telefone}</td><td>{d.chavePix}<p className="text-xs text-foreground/45">{d.banco}</p></td><td>{moeda(d.valorPadraoDiaria)}</td><td><StatusBadge status={d.ativo?"ATIVO":"INATIVO"}/></td><td><div className="flex gap-1"><button className="icon-action" onClick={()=>{setEditando(d);setModal(true)}}><Pencil/></button><button className="icon-action text-red-600" onClick={()=>confirm("Excluir diarista?")&&setLista(a=>a.filter(i=>i.id!==d.id))}><Trash2/></button></div></td></tr>)}</EntityTable></div><div className="diaristas-mobile diaristas-directory">{cadastros.map(d=><article key={d.id} className="diarista-mobile-card"><div className="diarista-mobile-head"><div><b>{d.nome}</b><small>{d.telefone}</small></div><StatusBadge status={d.ativo?"ATIVO":"INATIVO"}/></div><dl><div><dt>CPF</dt><dd>{d.cpf}</dd></div><div><dt>PIX / Banco</dt><dd>{d.chavePix}<small>{d.banco}</small></dd></div><div><dt>Diária</dt><dd>{moeda(d.valorPadraoDiaria)}</dd></div></dl><div className="diarista-directory-actions"><button className="btn-outline" onClick={()=>{setEditando(d);setModal(true)}}><Pencil size={14}/>Editar</button><button className="btn-danger-soft" onClick={()=>confirm("Excluir diarista?")&&setLista(a=>a.filter(i=>i.id!==d.id))}><Trash2 size={14}/>Excluir</button></div></article>)}</div></section>
 {confirmarDia&&<div className="modal-backdrop"><section className="card modal-panel max-w-2xl"><div className="modal-title"><div><h2>Resumo do dia</h2><p className="text-sm font-normal text-foreground/55">Confira os pagamentos antes de finalizar.</p></div><button onClick={()=>setConfirmarDia(false)}><X/></button></div><div className="space-y-2">{escalados.map(e=>{const d=lista.find(i=>i.id===e.diaristaId);return d&&<div key={e.id} className="flex items-center justify-between gap-2 rounded-xl border p-3"><div><b>{d.nome}</b><p className="text-xs text-foreground/50">PIX: {d.chavePix}</p></div><div className="text-right"><b className="mr-2">{moeda(e.valor)}</b><StatusBadge status={e.status}/></div></div>})}</div><div className="mt-5 flex justify-end gap-2"><button className="btn-outline" onClick={()=>setConfirmarDia(false)}>Voltar</button><button className="btn-primary" onClick={()=>{setEscalados([]);setConfirmarDia(false)}}><CalendarCheck2 size={17}/>Confirmar e finalizar</button></div></section></div>}
 {modal&&<div className="modal-backdrop"><form onSubmit={salvar} className="card modal-panel max-w-xl"><div className="modal-title"><h2>{editando?"Editar":"Novo"} diarista</h2><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2">{[["nome","Nome completo",editando?.nome],["cpf","CPF",editando?.cpf],["telefone","Telefone",editando?.telefone],["pix","Chave PIX",editando?.chavePix],["banco","Banco",editando?.banco],["valor","Valor da diária",editando?.valorPadraoDiaria]].map(([n,l,v])=><label key={String(n)}><span className="label">{l}</span><input name={String(n)} defaultValue={v} type={n==="valor"?"number":"text"} step="0.01" className="input" required/></label>)}</div><button className="btn-primary mt-6">Salvar cadastro</button></form></div>}
 </>;
}
