"use client";
import { useState } from "react";
import { Plus, X } from "lucide-react";
import { diaristasMock, registrosDiariaMock } from "@/lib/mock-data";
import type { Diarista } from "@/types";
import { moeda } from "@/lib/utils";
import { PageHeading } from "@/components/page-heading";
import { EntityTable } from "@/components/entity-table";
import { StatusBadge } from "@/components/status-badge";
export default function Diaristas(){const [lista,setLista]=useState(diaristasMock),[modal,setModal]=useState(false);function salvar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d:Diarista={id:crypto.randomUUID(),nome:String(f.get("nome")),cpf:String(f.get("cpf")),telefone:String(f.get("telefone")),chavePix:String(f.get("pix")),banco:String(f.get("banco")),valorPadraoDiaria:Number(f.get("valor")),ativo:true};setLista([d,...lista]);setModal(false)}return <><PageHeading title="Diaristas" description="Cadastros, diárias trabalhadas e pagamentos." action={<button className="btn-primary" onClick={()=>setModal(true)}><Plus size={17}/>Novo diarista</button>}/><section className="mb-5 grid gap-4 sm:grid-cols-3"><div className="card"><p className="text-sm text-foreground/50">Ativos</p><b className="text-2xl">{lista.filter(d=>d.ativo).length}</b></div><div className="card"><p className="text-sm text-foreground/50">Diárias pendentes</p><b className="text-2xl">{registrosDiariaMock.filter(r=>r.status!=="PAGO").length}</b></div><div className="card"><p className="text-sm text-foreground/50">Valor pendente</p><b className="text-2xl">{moeda(registrosDiariaMock.filter(r=>r.status!=="PAGO").reduce((s,r)=>s+r.valor,0))}</b></div></section><EntityTable headers={["Nome","CPF","Telefone","PIX / Banco","Diária","Status"]}>{lista.map(d=><tr key={d.id}><td className="font-semibold">{d.nome}</td><td>{d.cpf}</td><td>{d.telefone}</td><td>{d.chavePix}<p className="text-xs text-foreground/45">{d.banco}</p></td><td>{moeda(d.valorPadraoDiaria)}</td><td><StatusBadge status={d.ativo?"ATIVO":"INATIVO"}/></td></tr>)}</EntityTable>{modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={salvar} className="card w-full max-w-xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">Novo diarista</h2><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2">{[["nome","Nome completo"],["cpf","CPF"],["telefone","Telefone"],["pix","Chave PIX"],["banco","Banco"],["valor","Valor da diária"]].map(([n,l])=><label key={n}><span className="label">{l}</span><input name={n} type={n==="valor"?"number":"text"} step="0.01" className="input" required/></label>)}</div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Cancelar</button><button className="btn-primary">Cadastrar</button></div></form></div>}</>}
