import Link from "next/link";
import { AlertTriangle, Banknote, CalendarClock, CheckCircle2, ShoppingCart, UsersRound } from "lucide-react";
import { contasPagarMock, registrosDiariaMock, solicitacoesMock, tarefasMock } from "@/lib/mock-data";
import { moeda, dataBr } from "@/lib/utils";
import { StatusBadge } from "@/components/status-badge";
const cards=[
  {t:"Contas pendentes",v:moeda(contasPagarMock.filter(c=>c.status==="PENDENTE").reduce((s,c)=>s+c.valor,0)),i:Banknote,c:"text-amber-600",l:"/contas"},
  {t:"Boletos vencidos",v:String(contasPagarMock.filter(c=>c.status==="VENCIDO").length),i:AlertTriangle,c:"text-red-600",l:"/contas"},
  {t:"Diárias pendentes",v:String(registrosDiariaMock.filter(r=>r.status!=="PAGO").length),i:UsersRound,c:"text-blue-600",l:"/diaristas"},
  {t:"Aguardando aprovação",v:String(solicitacoesMock.filter(s=>s.status==="AGUARDANDO_APROVACAO").length),i:ShoppingCart,c:"text-purple-600",l:"/compras"}
];
export default function Dashboard(){return <><div className="mb-6"><p className="text-sm font-semibold text-gold">SEGUNDA-FEIRA, 22 DE SETEMBRO</p><h1 className="mt-1 text-3xl font-bold">Bom dia, Carlos!</h1><p className="text-foreground/55">Aqui está o resumo mais importante do restaurante.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({t,v,i:Icon,c,l})=><Link href={l} className="card transition hover:-translate-y-0.5" key={t}><div className="flex items-start justify-between"><div><p className="text-sm text-foreground/55">{t}</p><p className="mt-2 text-2xl font-bold">{v}</p></div><span className={`rounded-xl bg-muted p-2.5 ${c}`}><Icon size={20}/></span></div></Link>)}</section><section className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="card"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Próximos vencimentos</h2><p className="text-sm text-foreground/50">Contas que exigem atenção</p></div><Link href="/contas" className="text-sm font-semibold text-primary">Ver todas</Link></div><div className="space-y-3">{contasPagarMock.slice(0,3).map(c=><div key={c.id} className="flex flex-wrap items-center gap-3 rounded-xl border p-3"><CalendarClock className="text-gold" size={20}/><div className="min-w-[180px] flex-1"><p className="font-semibold">{c.descricao}</p><p className="text-xs text-foreground/50">{c.fornecedorNome} • {dataBr(c.dataVencimento)}</p></div><b>{moeda(c.valor)}</b><StatusBadge status={c.status}/></div>)}</div></div><div className="card"><div className="mb-4 flex items-center gap-2"><CheckCircle2 className="text-success"/><h2 className="font-bold">Tarefas prioritárias</h2></div><div className="space-y-3">{tarefasMock.filter(t=>t.status!=="CONCLUIDA").map(t=><div key={t.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-2"><p className="font-semibold">{t.titulo}</p><StatusBadge status={t.prioridade}/></div><p className="mt-2 text-xs text-foreground/50">{t.responsavelNome} • prazo {dataBr(t.prazo)}</p></div>)}</div></div></section></>}
