"use client";
import { useMemo, useState } from "react";
import { ChevronDown, ChevronUp, PackagePlus, Pencil, Plus, Trash2, X } from "lucide-react";
import { fornecedoresMock } from "@/lib/mock-data";
import type { Fornecedor, ProdutoFornecedor } from "@/types";
import { moeda } from "@/lib/utils";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { TableFilter } from "@/components/table-filter";

const categorias = ["Carnes e Aves","Bebidas","Hortifruti","Embalagens","Descartáveis","Laticínios","Mercearia","Padaria","Pescados","Limpeza e Higiene","Temperos e Condimentos","Gás e Energia","Manutenção","Uniformes","Serviços","Outro"];

export default function Fornecedores(){
  const [lista,setLista]=useState(fornecedoresMock),[busca,setBusca]=useState(""),[categoria,setCategoria]=useState("Todas");
  const [modal,setModal]=useState<"fornecedor"|"produtos"|null>(null),[editando,setEditando]=useState<Fornecedor|null>(null),[aberto,setAberto]=useState<string|null>(null);
  const dados=useMemo(()=>lista.filter(f=>(f.nomeFantasia+f.documento+f.responsavel).toLowerCase().includes(busca.toLowerCase())&&(categoria==="Todas"||f.categorias.includes(categoria))),[lista,busca,categoria]);
  function salvarFornecedor(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const item:Fornecedor={id:editando?.id||crypto.randomUUID(),nomeFantasia:String(d.get("nome")),documento:String(d.get("documento")),responsavel:String(d.get("responsavel")),telefone:String(d.get("telefone")),email:String(d.get("email")),categorias:[String(d.get("categoria"))],ativo:d.get("ativo")==="on",totalComprado:editando?.totalComprado||0,produtos:editando?.produtos||[]};setLista(a=>editando?a.map(x=>x.id===item.id?item:x):[item,...a]);setModal(null);setEditando(null)}
  function adicionarProduto(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editando)return;const d=new FormData(e.currentTarget);const produto:ProdutoFornecedor={id:crypto.randomUUID(),nome:String(d.get("produto")),unidade:String(d.get("unidade")),valor:Number(d.get("valor"))};setLista(a=>a.map(f=>f.id===editando.id?{...f,produtos:[...(f.produtos||[]),produto]}:f));setEditando(a=>a?{...a,produtos:[...(a.produtos||[]),produto]}:a);e.currentTarget.reset()}
  function removerProduto(id:string){if(!editando)return;setLista(a=>a.map(f=>f.id===editando.id?{...f,produtos:(f.produtos||[]).filter(p=>p.id!==id)}:f));setEditando(a=>a?{...a,produtos:(a.produtos||[]).filter(p=>p.id!==id)}:a)}
  return <>
    <PageHeading title="Fornecedores" description="Cadastros, produtos vinculados e compras do mês." action={<button className="btn-primary" onClick={()=>{setEditando(null);setModal("fornecedor")}}><Plus size={17}/>Novo fornecedor</button>}/>
    <div className="mb-4 grid gap-3 md:grid-cols-[1fr_260px]"><TableFilter value={busca} onChange={setBusca} placeholder="Buscar fornecedor, CPF/CNPJ ou responsável..."/><select className="input" value={categoria} onChange={e=>setCategoria(e.target.value)}><option>Todas</option>{categorias.map(c=><option key={c}>{c}</option>)}</select></div>
    <div className="space-y-3">{dados.map(f=><article key={f.id} className="card overflow-hidden p-0"><div className="grid items-center gap-3 p-4 md:grid-cols-[1.4fr_1fr_1fr_1fr_auto]"><button className="flex items-center gap-2 text-left font-semibold" onClick={()=>setAberto(aberto===f.id?null:f.id)}>{aberto===f.id?<ChevronUp size={17}/>:<ChevronDown size={17}/>}<span>{f.nomeFantasia}<small className="block font-normal text-foreground/45">{f.documento}</small></span></button><div className="text-sm">{f.responsavel}<small className="block text-foreground/45">{f.telefone}</small></div><div className="text-sm">{f.categorias.join(", ")}<small className="block text-foreground/45">CPF/CNPJ</small></div><div><b>{moeda(f.totalComprado)}</b><small className="block text-foreground/45">Comprado neste mês</small></div><div className="flex items-center gap-2"><StatusBadge status={f.ativo?"ATIVO":"INATIVO"}/><button className="icon-action" title="Editar" onClick={()=>{setEditando(f);setModal("fornecedor")}}><Pencil/></button><button className="btn-outline" onClick={()=>{setEditando(f);setModal("produtos")}}><PackagePlus size={16}/>Produtos</button></div></div>{aberto===f.id&&<div className="border-t bg-orange-50/50 p-4"><h3 className="mb-2 font-semibold">Produtos deste fornecedor</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(f.produtos||[]).map(p=><div key={p.id} className="rounded-xl border bg-white p-3"><b>{p.nome}</b><p className="text-sm text-foreground/55">{p.unidade} · {moeda(p.valor)}</p></div>)}{!f.produtos?.length&&<p className="text-sm text-foreground/50">Nenhum produto cadastrado.</p>}</div></div>}</article>)}</div>
    {modal==="fornecedor"&&<div className="modal-backdrop"><form className="card modal-panel" onSubmit={salvarFornecedor}><div className="modal-title"><h2>{editando?"Editar":"Novo"} fornecedor</h2><button type="button" onClick={()=>setModal(null)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Nome fantasia</span><input className="input" name="nome" defaultValue={editando?.nomeFantasia} required/></label><label><span className="label">CPF/CNPJ</span><input className="input" name="documento" defaultValue={editando?.documento} required/></label><label><span className="label">Responsável</span><input className="input" name="responsavel" defaultValue={editando?.responsavel} required/></label><label><span className="label">Telefone</span><input className="input" name="telefone" defaultValue={editando?.telefone} required/></label><label><span className="label">E-mail</span><input className="input" type="email" name="email" defaultValue={editando?.email} required/></label><label><span className="label">Categoria</span><select className="input" name="categoria" defaultValue={editando?.categorias[0]}>{categorias.map(c=><option key={c}>{c}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" name="ativo" defaultChecked={editando?.ativo??true}/>Fornecedor ativo</label></div><button className="btn-primary mt-6">Salvar fornecedor</button></form></div>}
    {modal==="produtos"&&editando&&<div className="modal-backdrop"><div className="card modal-panel"><div className="modal-title"><div><h2>Produtos de {editando.nomeFantasia}</h2><p className="text-sm text-foreground/50">Esta lista aparecerá nas solicitações.</p></div><button onClick={()=>setModal(null)}><X/></button></div><form className="grid gap-3 sm:grid-cols-[1fr_130px_130px_auto]" onSubmit={adicionarProduto}><input className="input" name="produto" placeholder="Nome do produto" required/><input className="input" name="unidade" placeholder="Unidade" required/><input className="input" name="valor" type="number" step=".01" placeholder="Valor" required/><button className="btn-primary"><Plus size={16}/>Adicionar</button></form><div className="mt-5 space-y-2">{(editando.produtos||[]).map(p=><div key={p.id} className="flex items-center justify-between rounded-xl border p-3"><span><b>{p.nome}</b><small className="ml-2 text-foreground/50">{p.unidade} · {moeda(p.valor)}</small></span><button className="icon-action text-red-600" onClick={()=>removerProduto(p.id)}><Trash2/></button></div>)}</div></div></div>}
  </>
}
